-- PRIMARY KEY DEFINITIONS

ALTER TABLE CUSTOMER ADD CONSTRAINT CustomerPK PRIMARY KEY (CustomerID);

ALTER TABLE PET ADD CONSTRAINT PetPK PRIMARY KEY (PetID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EmployeePK PRIMARY KEY (EmployeeID);

ALTER TABLE SERVICE ADD CONSTRAINT ServicePK PRIMARY KEY (ServiceID);

ALTER TABLE APPOINTMENT ADD CONSTRAINT DatePK PRIMARY KEY (VisitDate, CustomerID);




-- FOREIGN KEY DEFINITIONS

ATLER TABLE EMPLOYEE
ADD CONSTRAINT 
