-- PRIMARY KEY DEFINITIONS
ALTER TABLE CUSTOMER ADD CONSTRAINT CustomerPK PRIMARY KEY (CustomerID);

ALTER TABLE PET ADD CONSTRAINT PetPK PRIMARY KEY (PetID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EmployeePK PRIMARY KEY (EmployeeID);

ALTER TABLE SERVICES ADD CONSTRAINT ServicesPK PRIMARY KEY (ServicesID);

ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentPK PRIMARY KEY (VisitDate);

ALTER TABLE OWNS ADD CONSTRAINT OwnsPK PRIMARY KEY (CustomerID, PetID);

ALTER TABLE PERFORM ADD CONSTRAINT PerformPK PRIMARY KEY (EmployeeID, ServicesID);

-- FOREIGN KEY DEFINITIONS
ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentPetFK FOREIGN KEY (PetID) REFERENCES PET (PetID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentEmployeeFK FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE (EmployeeID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentServicesFK FOREIGN KEY (ServicesID) REFERENCES SERVICES (ServicesID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentCustomerFK FOREIGN KEY (CustomerID) REFERENCES CUSTOMER (CustomerID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE OWNS ADD CONSTRAINT OwnedByPet FOREIGN KEY (PetID) REFERENCES PET (PetID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE OWNS ADD CONSTRAINT OwnedByCust FOREIGN KEY (CustomerID) REFERENCES CUSTOMER (CustomerID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PERFORM ADD CONSTRAINT PerformedByEmp FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE (EmployeeID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PERFORM ADD CONSTRAINT PerformedByServ FOREIGN KEY (ServicesID) REFERENCES SERVICES (ServicesID) ON UPDATE CASCADE ON DELETE CASCADE;