
-- PRIMARY KEY DEFINITIONS
ALTER TABLE CUSTOMER ADD CONSTRAINT CustomerPK PRIMARY KEY (CustomerID);

ALTER TABLE PET ADD CONSTRAINT PetPK PRIMARY KEY (PetID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EmployeePK PRIMARY KEY (EmployeeID);

ALTER TABLE SERVICES ADD CONSTRAINT ServicesPK PRIMARY KEY (ServicesID);

ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentPK PRIMARY KEY (VisitDate, CustomerID, EmployeeID);

-- FOREIGN KEY DEFINITIONS
ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentCustomerFK FOREIGN KEY (CustomerID) REFERENCES CUSTOMER (CustomerID) ON UPDATE CASCADE;

ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentEmployeeFK FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE (EmployeeID) ON UPDATE CASCADE;

ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentServicesFK FOREIGN KEY (ServicesID) REFERENCES SERVICES (ServicesID) ON UPDATE CASCADE;

ALTER TABLE APPOINTMENT ADD CONSTRAINT AppointmentPetFK FOREIGN KEY (PetID) REFERENCES PET (PetID) ON UPDATE CASCADE;

ALTER TABLE PET ADD CONSTRAINT PetOwnerFK FOREIGN KEY (CustomerID) REFERENCES CUSTOMER (CustomerID) ON UPDATE CASCADE;