-- VÄLJ ALLA FRÅN KUNDER
select * from CUSTOMER;

-- VÄLJ ALLA FRÅN DJUR
select * from PET;

-- VÄLJ ALLA FRÅN TJÄNSTER
select * from SERVICES;

-- VÄLJ ALLA FRÅN ANSTÄLLDA
select * from EMPLOYEE;

-- VÄLJ ALLA FRÅN BOKNING
select * from APPOINTMENT;

-- VÄLJ ALLA KUNDER DÄR STAT INTE ÄR WA
select * from CUSTOMER WHERE CustomerState != 'WA';

-- VÄLJ ALLA KUNDER DÄR NAMN STARTAR PÅ A
select * from CUSTOMER WHERE CustomerName LIKE 'A%';

-- VÄLJ ALLA DJUR DÄR FÖDELSEDAGEN ÄR MELLAN 1983-1993
select * from PET WHERE DoB BETWEEN '1983-01-01' AND '1993-12-31';

-- VÄLJ SNITTPRISET FRÅN TJÄNSTER OCH GRUPPERA DEM VIA PRIS
select avg(Price) AS PriceAverage, Price, ServicesID FROM SERVICES GROUP BY Price;

-- VÄLJ SNITTPRISET FRÅN TJÄNSTER OCH GRUPPERA DEM VIA PRIS DÄR MEDELPRISET ÄR HÖGRE ÄN 40
select avg(Price) AS PriceAverage, Price, ServicesID FROM SERVICES GROUP BY Price HAVING PriceAverage > 40;

-- VÄLJ ALLA DJUR FRÅN PET OCH SORTERA DEM BASERAT PÅ FÖDELSEDAG
select * from PET ORDER BY DoB;

-- UPPDATERA DJUR DÄR ID = 104 OCH SÄTT RAS TILL Unkown
UPDATE PET SET Breed = 'Unknown' WHERE PetID = 104;

-- VÄLJ ALLA DJUR FRÅN PET OCH SORTERA DEM BASERAT PÅ FÖDELSEDAG
select * from PET ORDER BY DoB;

-- VÄLJ ALLA ANSTÄLLDA DÄR UTBILDNING = BS.
select * FROM EMPLOYEE WHERE Degree IN (SELECT Degree FROM EMPLOYEE WHERE Degree = 'BS.');

-- VÄLJ SNITTPRISET som PRICEAAV FRÅN TJÄNSTER
select avg(Price) as priceAV FROM SERVICES;